"""Gemini AI client for ThreatLens.

Provides:
- `generate_hypothesis(graph_summary: str) -> str`
- `get_mock_hypothesis() -> str`

Loads `GEMINI_API_KEY` from a .env file using python-dotenv and uses
the `google-generativeai` library to call Gemini. If the API key is
missing or the API call fails, the mock hypothesis is returned.
"""
from __future__ import annotations

import os
from typing import Any

from dotenv import load_dotenv

try:
    from google import genai
except Exception:  # pragma: no cover - library may be unavailable in test env
    genai = None


# Load environment variables from .env
load_dotenv()


MOCK_HYPOTHESIS = (
    "🔴 THREAT ASSESSMENT — APT INTRUSION DETECTED\n"
    "Confidence: HIGH | Generated by AI Hypothesis Engine\n\n"
    "🎯 ATTACK TYPE\n"
    "Multi-stage APT with financial targeting.\n"
    "Entry via phishing → Emotet → Cobalt Strike → Lateral Movement → Domain Escalation.\n\n"
    "🖥️ COMPROMISED HOSTS\n"
    "• FIN-DESK-042  — CRITICAL  (Initial infection, Emotet executed)\n"
    "• DC01          — HIGH      (Mimikatz credential dump detected)\n"
    "• EXEC-WS-01    — HIGH      (Cobalt Strike Beacon active)\n\n"
    "👤 SUSPICIOUS USERS\n"
    "• jsmith   — CRITICAL  (Used for lateral movement to DC01)\n"
    "• tlarson  — MEDIUM    (Active during infection window)\n\n"
    "🌐 MALICIOUS IPs\n"
    "• 185.220.101.45  — C2 Server (Cobalt Strike traffic)\n"
    "• 45.33.32.156    — Exfiltration target\n\n"
    "✅ IMMEDIATE ACTIONS\n"
    "1. ISOLATE  → FIN-DESK-042 and EXEC-WS-01 now\n"
    "2. RESET    → jsmith and tlarson credentials immediately\n"
    "3. BLOCK    → 185.220.101.45 and 45.33.32.156 at firewall\n"
)


def get_mock_hypothesis() -> str:
    """Return the exact hardcoded mock threat report string."""
    return MOCK_HYPOTHESIS


def generate_hypothesis(graph_summary: str) -> str:
    """Generate a threat assessment report from a cyber attack graph summary.

    If the Gemini API is unavailable or an error occurs, the function returns
    the hardcoded mock hypothesis.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    print(f"API Key present: {bool(api_key)}")
    if not api_key:
        print("No API key found, returning mock")
        return get_mock_hypothesis()

    try:
        print(f"Calling Gemini with summary length: {len(graph_summary)}")
        client = genai.Client(api_key=api_key)
        prompt = f"""You are a senior cybersecurity threat analyst working in a SOC.
Analyze this network graph data from a corporate network and generate a threat assessment report.

GRAPH DATA:
{graph_summary}

Generate a structured threat report with exactly these sections:
🔴 THREAT ASSESSMENT — [THREAT LEVEL: CRITICAL/HIGH/MEDIUM/LOW]
Confidence: [HIGH/MEDIUM/LOW] | Generated by AI Hypothesis Engine

🎯 ATTACK TYPE
[Describe the attack pattern and kill chain]

🖥️ COMPROMISED HOSTS
[List each compromised host with severity and what was detected]

👤 SUSPICIOUS USERS
[List suspicious users with their role and why they are suspicious]

🌐 MALICIOUS IPs
[List malicious IPs with their role in the attack]

✅ IMMEDIATE ACTIONS
[Number each action: ISOLATE/BLOCK/RESET/INVESTIGATE]

Be specific, use the actual node names from the graph data. Keep it concise and actionable."""

        response = client.models.generate_content(
            model="gemini-2.5-flash-lite",
            contents=prompt
        )
        print(f"Gemini response received: {len(response.text)} chars")
        return response.text
    except Exception as e:
        print(f"Gemini error: {e}")
        return get_mock_hypothesis()


if __name__ == "__main__":
    # Print the mock hypothesis (useful when API is unavailable)
    print(get_mock_hypothesis())
