"""Gemini AI client for ThreatLens.

Provides:
- `generate_hypothesis(graph_summary: str) -> str`
- `get_mock_hypothesis() -> str`

Loads `GEMINI_API_KEY` from a .env file using python-dotenv and uses
the `google-generativeai` library to call Gemini. If the API key is
missing or the API call fails, the mock hypothesis is returned.
"""
from __future__ import annotations

import os
from typing import Any

from dotenv import load_dotenv

try:
    from google import genai
except Exception:  # pragma: no cover - library may be unavailable in test env
    genai = None


# Load environment variables from .env
load_dotenv()


MOCK_HYPOTHESIS = (
    "🔴 THREAT ASSESSMENT — APT INTRUSION DETECTED\n"
    "Confidence: HIGH | Generated by AI Hypothesis Engine\n\n"
    "🎯 ATTACK TYPE\n"
    "Multi-stage APT with financial targeting.\n"
    "Entry via phishing → Emotet → Cobalt Strike → Lateral Movement → Domain Escalation.\n\n"
    "🖥️ COMPROMISED HOSTS\n"
    "• FIN-DESK-042  — CRITICAL  (Initial infection, Emotet executed)\n"
    "• DC01          — HIGH      (Mimikatz credential dump detected)\n"
    "• EXEC-WS-01    — HIGH      (Cobalt Strike Beacon active)\n\n"
    "👤 SUSPICIOUS USERS\n"
    "• jsmith   — CRITICAL  (Used for lateral movement to DC01)\n"
    "• tlarson  — MEDIUM    (Active during infection window)\n\n"
    "🌐 MALICIOUS IPs\n"
    "• 185.220.101.45  — C2 Server (Cobalt Strike traffic)\n"
    "• 45.33.32.156    — Exfiltration target\n\n"
    "✅ IMMEDIATE ACTIONS\n"
    "1. ISOLATE  → FIN-DESK-042 and EXEC-WS-01 now\n"
    "2. RESET    → jsmith and tlarson credentials immediately\n"
    "3. BLOCK    → 185.220.101.45 and 45.33.32.156 at firewall\n"
)


def get_mock_hypothesis() -> str:
    """Return the exact hardcoded mock threat report string."""
    return MOCK_HYPOTHESIS


def generate_hypothesis(graph_summary: str) -> str:
    """Generate a threat assessment report from a cyber attack graph summary.

    If the Gemini API is unavailable or an error occurs, the function returns
    the hardcoded mock hypothesis.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key or genai is None:
        return get_mock_hypothesis()

    try:
        client = genai.Client(api_key=api_key)

        system_prompt = (
            "You are a senior threat analyst. Given a summary of a cyber attack graph, "
            "produce a concise, formatted threat assessment report including: "
            "attack type, compromised hosts, suspicious users, malicious IPs, and immediate actions. "
            "Be specific and prioritize high-confidence findings."
        )

        user_prompt = f"Graph summary:\n\n{graph_summary}\n\nProduce the assessment as a single formatted text report."

        prompt = system_prompt + "\n\n" + user_prompt
        response = client.models.generate_content(model="gemini-1.5-flash", contents=prompt)
        return response.text
    except Exception:
        return get_mock_hypothesis()


if __name__ == "__main__":
    # Print the mock hypothesis (useful when API is unavailable)
    print(get_mock_hypothesis())
